services:
  MongoDB:
    image: mongo:6-jammy
    container_name: tp-final-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'", "--quiet" ]
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
      - /tmp/tp-final-mongo:/data/db
