services:
  MySQL:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfinal22
    ports:
      - 4306:3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 3s
      timeout: 30s
      retries: 10
